"""Generate docs/DATA_DICTIONARY.md from the schema definitions.

Walks the fiscal + stars bqload registries and the SAFS schema modules and
emits one Markdown section per BigQuery table: its `project.dataset.table`
location, data provenance, canonical-source annotation (for facts that also
live in SAFS), and a column table (name, BigQuery type, key flag, doc).

The file is GENERATED -- edit the schema modules, not the Markdown.

    python3 -m extractors.bqload.gen_dictionary -o docs/DATA_DICTIONARY.md
"""

import argparse
import importlib
from pathlib import Path

from .spec import schema_fieldnames


PROJECT = "sps-btn-data"

_BQ_TYPE = {
    "string": "STRING",
    "int": "INT64",
    "decimal": "NUMERIC",
    "boolean": "BOOL",
    "timestamp": "TIMESTAMP",
    "auto_primary_key": "INT64",
}

# SAFS schema module -> (bq_dataset, provenance). Mirrors
# gcloud_load_tables.bq_dataset_name (assessment -> ospi, else safs_<module>).
_SAFS = [
    ("f19x", "safs_f19x",
     "SAFS Access DB extract of F-195 (budget) + F-196 (actuals) filings "
     "(data/safs/f19x, data/safs/f196)."),
    ("s275", "safs_s275",
     "SAFS S-275 personnel database extract (data/safs/s275)."),
    ("domains", "safs_domains",
     "Decoded dimension/lookup tables built by the SAFS pipeline."),
    ("enrollment", "safs_enrollment",
     "SAFS P223 / historical enrollment extract (data/safs/p223)."),
    ("sqss", "safs_sqss", "OSPI SQSS AVRO source (data/sqss)."),
    ("assessment", "ospi", "OSPI assessment AVRO source (data/assessment)."),
]


def _rows_for_schema(schema):
    logical = {f["name"] for f in schema["fields"]
               if f.get("is_logical_key")}
    primary = {f["name"] for f in schema["fields"]
               if f.get("is_primary_key") or f["field_type"] == "auto_primary_key"}
    out = []
    for f in schema["fields"]:
        key = []
        if f["name"] in primary:
            key.append("PK")
        if f["name"] in logical:
            key.append("LK")
        out.append((f["name"], _BQ_TYPE.get(f["field_type"], f["field_type"]),
                    " ".join(key), (f.get("doc") or "").replace("\n", " ")))
    return out


def _table_section(bq_dataset, spec_or_schema, provenance, canonical=None):
    schema = getattr(spec_or_schema, "schema", spec_or_schema)
    name = schema["name"]
    lines = [f"### `{PROJECT}.{bq_dataset}.{name}`", ""]
    if schema.get("doc"):
        lines += [schema["doc"].replace("\n", " "), ""]
    lines += [f"- **Provenance:** {provenance}"]
    if canonical and canonical.status == "duplicate":
        lines += [f"- **⚠ Canonical source:** prefer `{canonical.prefer}` "
                  f"-- {canonical.note}"]
    elif canonical and canonical.status == "unique":
        lines += ["- **Canonical source:** this table (facts appear nowhere "
                  "else)."]
    lines += ["", "| column | type | key | description |",
              "|---|---|---|---|"]
    for n, t, k, d in _rows_for_schema(schema):
        lines.append(f"| `{n}` | {t} | {k} | {d} |")
    lines.append("")
    return "\n".join(lines)


def build_markdown() -> str:
    from ..fiscal.registry import FAMILY as FISCAL
    from ..stars.registry import FAMILY as STARS

    parts = [
        "# SPS data-tools BigQuery data dictionary",
        "",
        "GENERATED by `extractors/bqload/gen_dictionary.py` -- edit the schema "
        "modules, not this file.",
        "",
        f"All tables live in BigQuery project `{PROJECT}`. Fiscal and stars "
        "tables are parsed from OSPI PDFs; SAFS tables are extracted from OSPI "
        "Access databases. Where a fiscal table duplicates SAFS data, the "
        "canonical source is noted.",
        "",
        "## Contents",
        "",
    ]
    sections = []

    def add_family(title, family):
        body = [f"## {title} (`{family.bq_dataset}`)", ""]
        for spec in sorted(family.tables, key=lambda t: t.table):
            prov = (f"Parsed from OSPI PDFs under `{spec.corpus}` "
                    f"({spec.kind}).")
            body.append(_table_section(family.bq_dataset, spec, prov,
                                       spec.canonical))
        sections.append("\n".join(body))

    add_family("Fiscal", FISCAL)
    add_family("STARS", STARS)

    safs_body = ["## SAFS (Access-database extracts)", ""]
    for module, bq_dataset, prov in _SAFS:
        mod = importlib.import_module(f"extractors.safs.schemas.{module}")
        for schema in getattr(mod, "ALL_SCHEMAS", []):
            safs_body.append(_table_section(bq_dataset, schema, prov))
    sections.append("\n".join(safs_body))

    # Build a small table-of-contents.
    toc = []
    for title, fam in (("Fiscal", FISCAL), ("STARS", STARS)):
        toc.append(f"- **{title}** (`{fam.bq_dataset}`): "
                   + ", ".join(sorted(t.table for t in fam.tables)))
    toc.append("- **SAFS**: datasets "
               + ", ".join(sorted({d for _, d, _ in _SAFS})))
    parts.append("\n".join(toc))
    parts.append("")
    parts.extend(sections)
    return "\n".join(parts) + "\n"


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("-o", "--out", default="docs/DATA_DICTIONARY.md")
    args = p.parse_args()
    md = build_markdown()
    Path(args.out).write_text(md)
    print(f"wrote {args.out} ({md.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
